name: build-clients-service

on:
  push:
    branches: [ main ]
    paths:
      - clients-service/**
      - commons-api/**
      - .github/workflows/build-workflow.yml
      - .github/workflows/build-clients-service.yml

jobs:
  run:
    uses: ./.github/workflows/build-workflow.yml
    with:
      service: clients-service