on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup cache
        id: cache
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: |
            pom.xml
            **/pom.xml

      - name: Build application
        run: mvn clean package --projects :${{ inputs.service }} --also-make --batch-mode
