name: build-payments-service

on:
  push:
    branches: [ main ]
    paths:
      - payments-service/**
      - commons-api/**
      - .github/workflows/build-payments-service.yml

jobs:
  run:
    uses: ./.github/workflows/build-workflow.yml
    with:
      service: payments-service